# Generated by Django 3.2.16 on 2023-01-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSales',
            fields=[
                ('SaleId', models.AutoField(primary_key=True, serialize=False)),
                ('Manufacturer', models.CharField(max_length=20)),
                ('CarModel', models.CharField(max_length=20)),
                ('Sales_in_thousands', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Price_in_thousands', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Engine_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Horsepower', models.IntegerField()),
                ('Fuel_efficiency', models.IntegerField()),
            ],
        ),
    ]
