# Generated by Django 3.2.16 on 2023-01-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsales',
            old_name='CarModel',
            new_name='Model',
        ),
    ]
